# Generated by Django 4.2.5 on 2023-09-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True, verbose_name='user ID telegram')),
                ('user_name', models.CharField(max_length=30, verbose_name='user_name telegram')),
                ('full_name', models.CharField(max_length=70, verbose_name="Повне ім'я")),
            ],
            options={
                'verbose_name': 'Профіль',
                'verbose_name_plural': 'Профілі',
                'ordering': ('id',),
            },
        ),
    ]
