# Generated by Django 4.2.5 on 2023-09-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngtg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=70, verbose_name="Повне ім'я"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='user_name telegram'),
        ),
    ]
