# Generated by Django 4.2.5 on 2023-09-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngtg', '0002_alter_profile_full_name_alter_profile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name="Повне ім'я"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='user_name telegram'),
        ),
    ]
